/run/initialize
/run/printProgress 10000
/Sim/setSeed 21454
/Sim/setOutputFileName Output_Pb212_PC3_PIP_Activity3kBq_Membrane_Thread_8.root
/Sim/SetInitialRadionuclide_Z 82
/Sim/SetInitialRadionuclide_A 212
/Sim/SetInitialRadionuclide_excitationEnergy 0.0
/Sim/DefineInitialRadionuclide
/Sim/SetInitialRadionuclide_location 1
/Sim/SetSampleActivity 3
/Sim/SetCellLineName PC3_PIP
/Sim/SetDecayCurveRadionuclide
/run/beamOn 21414
