/run/initialize
/run/printProgress 10000
/Sim/setSeed 345823
/Sim/setOutputFileName Output_Pb212_PC3_PIP_Activity50kBq_Membrane_Thread_27.root
/Sim/SetInitialRadionuclide_Z 82
/Sim/SetInitialRadionuclide_A 212
/Sim/SetInitialRadionuclide_excitationEnergy 0.0
/Sim/DefineInitialRadionuclide
/Sim/SetInitialRadionuclide_location 1
/Sim/SetSampleActivity 50
/Sim/SetCellLineName PC3_PIP
/Sim/SetDecayCurveRadionuclide
/run/beamOn 345783
