/run/initialize
/run/printProgress 10000
/Sim/setSeed 678268
/Sim/setOutputFileName Output_Pb212_PC3_PIP_Activity100kBq_Membrane_Thread_23.root
/Sim/SetInitialRadionuclide_Z 82
/Sim/SetInitialRadionuclide_A 212
/Sim/SetInitialRadionuclide_excitationEnergy 0.0
/Sim/DefineInitialRadionuclide
/Sim/SetInitialRadionuclide_location 1
/Sim/SetSampleActivity 100
/Sim/SetCellLineName PC3_PIP
/Sim/SetDecayCurveRadionuclide
/run/beamOn 678228
