/run/initialize
/run/printProgress 10000
/Sim/setSeed 38054
/Sim/setOutputFileName Output_Pb212_C4_2_Activity150kBq_Cytoplasm_Thread_4.root
/Sim/SetInitialRadionuclide_Z 82
/Sim/SetInitialRadionuclide_A 212
/Sim/SetInitialRadionuclide_excitationEnergy 0.0
/Sim/DefineInitialRadionuclide
/Sim/SetInitialRadionuclide_location 2
/Sim/SetSampleActivity 150
/Sim/SetCellLineName C4_2
/Sim/SetDecayCurveRadionuclide
/run/beamOn 38014
