/run/initialize
/run/printProgress 10000
/Sim/setSeed 17967
/Sim/setOutputFileName Output_Pb212_C4_2_Activity50kBq_Membrane_Thread_21.root
/Sim/SetInitialRadionuclide_Z 82
/Sim/SetInitialRadionuclide_A 212
/Sim/SetInitialRadionuclide_excitationEnergy 0.0
/Sim/DefineInitialRadionuclide
/Sim/SetInitialRadionuclide_location 1
/Sim/SetSampleActivity 50
/Sim/SetCellLineName C4_2
/Sim/SetDecayCurveRadionuclide
/run/beamOn 17927
