#!/bin/bash
#SBATCH --account=NN9895K
#SBATCH --job-name AlphaTherapy
#SBATCH --mail-type=ALL
#SBATCH --mail-user=idapro@fys.uio.no
#SBATCH --time=0-40:00:00
#SBATCH --mem-per-cpu=32G
#SBATCH --ntasks=1 --cpus-per-task=1
#SBATCH --array=50

EXECUTABLE=main

ACTIVITY=$SLURM_ARRAY_TASK_ID
OUTPUTFILE="TerminalOutput_C4_2_${ACTIVITY}kBq.txt"

CELLLINE=C4_2
CELLGEOMETRY=D12RP
NUMBERITERATIONS=1
CASENUMBER=1


./$EXECUTABLE $CELLLINE $CELLGEOMETRY $ACTIVITY $NUMBERITERATIONS $CASENUMBER > $OUTPUTFILE