#!/bin/bash
#SBATCH --account=NN9895K
#SBATCH --job-name AlphaTherapy
#SBATCH --mail-type=ALL
#SBATCH --mail-user=idapro@fys.uio.no
#SBATCH --time=0-20:00:00
#SBATCH --mem-per-cpu=4G
#SBATCH --ntasks=1 --cpus-per-task=40
#SBATCH --array=1,3,5,10,25,50,75,100,150

EXECUTABLE=main

ACTIVITY=$SLURM_ARRAY_TASK_ID
OUTPUTFILE="TerminalOutput_C4_2_${ACTIVITY}kBq.txt"

CELLLINE=PC3_Flu
CELLGEOMETRY=D5CP
NUMBERITERATIONS=40
CASENUMBER=1


./$EXECUTABLE $CELLLINE $CELLGEOMETRY $ACTIVITY $NUMBERITERATIONS $CASENUMBER > $OUTPUTFILE