/run/initialize
/run/printProgress 10000
/Sim/setSeed 414639
/Sim/setOutputFileName Output_Pb212_C4_2_Activity150kBq_Solution_Thread_23.root
/Sim/SetInitialRadionuclide_Z 82
/Sim/SetInitialRadionuclide_A 212
/Sim/SetInitialRadionuclide_excitationEnergy 0.0
/Sim/DefineInitialRadionuclide
/Sim/SetInitialRadionuclide_location 0
/Sim/SetSampleActivity 150
/Sim/SetCellLineName C4_2
/Sim/SetDecayCurveRadionuclide
/run/beamOn 414599
