/run/initialize
/run/printProgress 10000
/Sim/setSeed 275418
/Sim/setOutputFileName Output_Pb212_C4_2_Activity100kBq_Solution_Thread_11.root
/Sim/SetInitialRadionuclide_Z 82
/Sim/SetInitialRadionuclide_A 212
/Sim/SetInitialRadionuclide_excitationEnergy 0.0
/Sim/DefineInitialRadionuclide
/Sim/SetInitialRadionuclide_location 0
/Sim/SetSampleActivity 100
/Sim/SetCellLineName C4_2
/Sim/SetDecayCurveRadionuclide
/run/beamOn 275378
