/run/initialize
/run/printProgress 10000
/Sim/setSeed 4676
/Sim/setOutputFileName Output_Pb212_PC3_PIP_Activity10kBq_Cytoplasm_Thread_21.root
/Sim/SetInitialRadionuclide_Z 82
/Sim/SetInitialRadionuclide_A 212
/Sim/SetInitialRadionuclide_excitationEnergy 0.0
/Sim/DefineInitialRadionuclide
/Sim/SetInitialRadionuclide_location 2
/Sim/SetSampleActivity 10
/Sim/SetCellLineName PC3_PIP
/Sim/SetDecayCurveRadionuclide
/run/beamOn 4636
