/run/initialize
/run/printProgress 10000
/Sim/setSeed 211857
/Sim/setOutputFileName Output_Pb212_PC3_PIP_Activity100kBq_Solution_Thread_8.root
/Sim/SetInitialRadionuclide_Z 82
/Sim/SetInitialRadionuclide_A 212
/Sim/SetInitialRadionuclide_excitationEnergy 0.0
/Sim/DefineInitialRadionuclide
/Sim/SetInitialRadionuclide_location 0
/Sim/SetSampleActivity 100
/Sim/SetCellLineName PC3_PIP
/Sim/SetDecayCurveRadionuclide
/run/beamOn 211847
