/run/initialize
/run/printProgress 10000
/Sim/setSeed 7189
/Sim/setOutputFileName Output_Pb212_PC3_PIP_Activity1kBq_Membrane_Thread_11.root
/Sim/SetInitialRadionuclide_Z 82
/Sim/SetInitialRadionuclide_A 212
/Sim/SetInitialRadionuclide_excitationEnergy 0.0
/Sim/DefineInitialRadionuclide
/Sim/SetInitialRadionuclide_location 1
/Sim/SetSampleActivity 1
/Sim/SetCellLineName PC3_PIP
/Sim/SetDecayCurveRadionuclide
/run/beamOn 7149
